<?php

namespace AppBundle\Repository;

/**
 * ElectoralListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectoralListRepository extends \Doctrine\ORM\EntityRepository
{
}
