<?php

namespace AppBundle\Repository;

/**
 * GroupOfCitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupOfCitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
