<?php

namespace AppBundle\Repository;

/**
 * NotificationEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
