<?php

namespace AppBundle\Repository;

/**
 * OriginalQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginalQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
